delivery-price:
  baseCost : 5.0
  addressRatio: 2.0
  fragileRatio: 1.2
  farRatio: 1.2
  weightRatio: 0.3
  volumeRatio: 0.2
server.port: 0
logging:
  level:
    org:
      zalando:
        logbook: TRACE
spring:
  jpa:
    properties.hibernate.format-sql: true
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    show-sql: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commerce-warehouse
    username: vxuser
    password: vxpasswd