spring:
  application:
    name: payment
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
eureka:
  instance:
    hostname: localhost
    port: 8761
    instance-id: "${spring.application.name}:${random.value}"
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
