spring:
  main:
    banner-mode: off
    log-startup-info: false
aggregator:
  kafkaHost: localhost
  kafkaPort: 9092
  groupId: snapshot
  sensorTopic: telemetry.sensors.v1
  snapshotTopic: telemetry.snapshots.v1