server.port: 0
spring:
  jpa:
    properties.hibernate.format-sql: true
    hibernate:
      ddl-auto: none
    database: POStGRE
    show-sql: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/commerce-shopping-store
    username: vxuser
    password: vxpasswd